name: 'Lint Filenames'
description: 'This github action validates if all files in a given folder match the given regex pattern.'
branding:
  icon: 'folder'
  color: white
inputs:
  path:
    description: 'The path to a directory or glob to check the filenames.'
    required: true
    default: './'
  pattern:
    description: 'The regex pattern to match for each of the files in the given directory'
    required: true
    default: '/.+/'
  globPattern:
    description: 'Glob pattern to use for specified path'
    required: false
  ignoreGlob:
    description: 'Glob patterns to ignore (multi-line)'
    required: false
outputs:
  total-files-analyzed:
    description: 'The number of files analyzed.'
runs:
  using: 'node16'
  main: 'dist/index.js'
